"""Create initial database schema

Revision ID: 5c368742a0f0
Revises: 
Create Date: 2026-07-14 18:03:25.702430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c368742a0f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('fs_uniquifier', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fs_uniquifier')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('coding_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('platform_link', sa.String(length=1000), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=False),
    sa.Column('revision_status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('solved_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            revision_status IN (\n                'Not Started',\n                'First Revision',\n                'Second Revision',\n                'Mastered'\n            )\n            ", name='ck_coding_problem_revision_status'),
    sa.CheckConstraint("\n            status IN (\n                'Unsolved',\n                'Solved',\n                'Revision Needed'\n            )\n            ", name='ck_coding_problem_status'),
    sa.CheckConstraint("difficulty IN ('Easy', 'Medium', 'Hard')", name='ck_coding_problem_difficulty'),
    sa.CheckConstraint('attempts >= 0', name='ck_coding_problem_attempts_non_negative'),
    sa.CheckConstraint('time_spent_minutes >= 0', name='ck_coding_problem_time_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coding_problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coding_problems_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_coding_problems_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_coding_problems_revision_status'), ['revision_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_coding_problems_solved_date'), ['solved_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_coding_problems_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_coding_problems_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_coding_problems_user_id'), ['user_id'], unique=False)

    op.create_table('daily_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('solved_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('solved_count >= 0', name='ck_daily_target_solved_non_negative'),
    sa.CheckConstraint('target_count > 0', name='ck_daily_target_count_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_date', name='uq_daily_target_user_date')
    )
    with op.batch_alter_table('daily_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_targets_target_date'), ['target_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_targets_user_id'), ['user_id'], unique=False)

    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    with op.batch_alter_table('daily_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_targets_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_targets_target_date'))

    op.drop_table('daily_targets')
    with op.batch_alter_table('coding_problems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coding_problems_user_id'))
        batch_op.drop_index(batch_op.f('ix_coding_problems_topic'))
        batch_op.drop_index(batch_op.f('ix_coding_problems_status'))
        batch_op.drop_index(batch_op.f('ix_coding_problems_solved_date'))
        batch_op.drop_index(batch_op.f('ix_coding_problems_revision_status'))
        batch_op.drop_index(batch_op.f('ix_coding_problems_platform'))
        batch_op.drop_index(batch_op.f('ix_coding_problems_difficulty'))

    op.drop_table('coding_problems')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    # ### end Alembic commands ###
